Repository CodIN-INU/codin-ticketing-api, pull requests merged in 2025-08, with the labels that each got.

#17 이벤트 참가자 Excel 추출 기능 추가
  build.gradle
  src/main/java/inu/codin/codinticketingapi/domain/admin/controller/ExcelController.java
  src/main/java/inu/codin/codinticketingapi/domain/admin/controller/ExcelControllerImpl.java
  src/main/java/inu/codin/codinticketingapi/domain/admin/controller/swagger/ExcelController.java
  src/main/java/inu/codin/codinticketingapi/domain/admin/dto/response/ExcelResponse.java
  src/main/java/inu/codin/codinticketingapi/domain/admin/exception/ExcelErrorCode.java
  src/main/java/inu/codin/codinticketingapi/domain/admin/exception/ExcelException.java
  src/main/java/inu/codin/codinticketingapi/domain/admin/service/ExcelService.java
  src/main/java/inu/codin/codinticketingapi/domain/ticketing/repository/ParticipationRepository.java
Labels: enhancement

#18 이벤트 참가자 Excel 추출 기능 추가 및 README 수정
  README.md
  build.gradle
  src/main/java/inu/codin/codinticketingapi/domain/admin/controller/ExcelController.java
  src/main/java/inu/codin/codinticketingapi/domain/admin/controller/ExcelControllerImpl.java
  src/main/java/inu/codin/codinticketingapi/domain/admin/controller/swagger/ExcelController.java
  src/main/java/inu/codin/codinticketingapi/domain/admin/dto/response/ExcelResponse.java
  src/main/java/inu/codin/codinticketingapi/domain/admin/exception/ExcelErrorCode.java
  src/main/java/inu/codin/codinticketingapi/domain/admin/exception/ExcelException.java
  src/main/java/inu/codin/codinticketingapi/domain/admin/service/ExcelService.java
  src/main/java/inu/codin/codinticketingapi/domain/ticketing/repository/ParticipationRepository.java
Labels: enhancement

#26 refactor: 티켓팅 도메인 피드백 적용
  src/main/java/inu/codin/codinticketingapi/domain/ticketing/dto/response/EventDetailResponse.java
  src/main/java/inu/codin/codinticketingapi/domain/ticketing/service/EventService.java
  src/main/java/inu/codin/codinticketingapi/domain/ticketing/service/ParticipationService.java
  src/main/java/inu/codin/codinticketingapi/domain/user/exception/UserErrorCode.java
Labels: bug, enhancement

#36 refactor: Sse 모듈 기능 개선 #35
  codin-ticketing-sse/build.gradle
  codin-ticketing-sse/src/main/java/inu/codin/codinticketingsse/CodinTicketingSseApplication.java
  codin-ticketing-sse/src/main/java/inu/codin/codinticketingsse/config/SecurityConfig.java
  codin-ticketing-sse/src/main/java/inu/codin/codinticketingsse/config/SwaggerConfig.java
  codin-ticketing-sse/src/main/java/inu/codin/codinticketingsse/sse/config/RedisStreamListenerConfig.java
  codin-ticketing-sse/src/main/java/inu/codin/codinticketingsse/sse/controller/SseController.java
  codin-ticketing-sse/src/main/java/inu/codin/codinticketingsse/sse/dto/SseEmitterTimeoutEvent.java
  codin-ticketing-sse/src/main/java/inu/codin/codinticketingsse/sse/monitor/SseConnectionMonitor.java
  codin-ticketing-sse/src/main/java/inu/codin/codinticketingsse/sse/repository/SseEmitterRepository.java
  codin-ticketing-sse/src/main/java/inu/codin/codinticketingsse/sse/repository/SseEmitterRepositoryImpl.java
  codin-ticketing-sse/src/main/java/inu/codin/codinticketingsse/sse/service/SseService.java
  codin-ticketing-sse/src/main/resources/application.yml
Labels: enhancement

#38 refactor: 수령자 리스트 조회 반환값 추가 및 SSE모듈 개선
  build.gradle
  codin-ticketing-sse/build.gradle
  codin-ticketing-sse/src/main/java/inu/codin/codinticketingsse/CodinTicketingSseApplication.java
  codin-ticketing-sse/src/main/java/inu/codin/codinticketingsse/config/SecurityConfig.java
  codin-ticketing-sse/src/main/java/inu/codin/codinticketingsse/config/SwaggerConfig.java
  codin-ticketing-sse/src/main/java/inu/codin/codinticketingsse/sse/config/RedisStreamListenerConfig.java
  codin-ticketing-sse/src/main/java/inu/codin/codinticketingsse/sse/controller/SseController.java
  codin-ticketing-sse/src/main/java/inu/codin/codinticketingsse/sse/dto/SseEmitterTimeoutEvent.java
  codin-ticketing-sse/src/main/java/inu/codin/codinticketingsse/sse/monitor/SseConnectionMonitor.java
  codin-ticketing-sse/src/main/java/inu/codin/codinticketingsse/sse/repository/SseEmitterRepository.java
  codin-ticketing-sse/src/main/java/inu/codin/codinticketingsse/sse/repository/SseEmitterRepositoryImpl.java
  codin-ticketing-sse/src/main/java/inu/codin/codinticketingsse/sse/service/SseService.java
  codin-ticketing-sse/src/main/resources/application.yml
  src/main/java/inu/codin/codinticketingapi/CodinTicketingApiApplication.java
  src/main/java/inu/codin/codinticketingapi/common/exception/GlobalExceptionHandler.java
  src/main/java/inu/codin/codinticketingapi/config/JpaConfig.java
  src/main/java/inu/codin/codinticketingapi/config/SecurityConfig.java
  src/main/java/inu/codin/codinticketingapi/domain/admin/dto/request/EventCreateRequest.java
  src/main/java/inu/codin/codinticketingapi/domain/admin/dto/request/EventUpdateRequest.java
  src/main/java/inu/codin/codinticketingapi/domain/admin/dto/response/EventParticipationProfilePageResponse.java
  src/main/java/inu/codin/codinticketingapi/domain/admin/scheduler/EventStatusScheduler.java
  src/main/java/inu/codin/codinticketingapi/domain/admin/service/EventAdminService.java
  src/main/java/inu/codin/codinticketingapi/domain/ticketing/controller/TicketingController.java
  src/main/java/inu/codin/codinticketingapi/domain/ticketing/dto/event/ParticipationCreatedEvent.java
  src/main/java/inu/codin/codinticketingapi/domain/ticketing/dto/event/ParticipationStatusChangedEvent.java
  src/main/java/inu/codin/codinticketingapi/domain/ticketing/dto/response/EventPageDetailResponse.java
  src/main/java/inu/codin/codinticketingapi/domain/ticketing/dto/response/EventPageResponse.java
  src/main/java/inu/codin/codinticketingapi/domain/ticketing/dto/response/EventParticipationHistoryPageResponse.java
  src/main/java/inu/codin/codinticketingapi/domain/ticketing/dto/response/ParticipationResponse.java
  src/main/java/inu/codin/codinticketingapi/domain/ticketing/redis/RedisParticipationService.java
  src/main/java/inu/codin/codinticketingapi/domain/ticketing/repository/EventRepository.java
  src/main/java/inu/codin/codinticketingapi/domain/ticketing/repository/ParticipationRepository.java
  src/main/java/inu/codin/codinticketingapi/domain/ticketing/service/ParticipationService.java
  src/main/java/inu/codin/codinticketingapi/domain/ticketing/service/TicketingService.java
  src/test/java/inu/codin/codinticketingapi/domain/ticketing/ParticipationIntegrationTest.java
  src/test/java/inu/codin/codinticketingapi/domain/ticketing/controller/EventControllerTest.java
  src/test/java/inu/codin/codinticketingapi/domain/ticketing/controller/TicketingControllerTest.java
  src/test/java/inu/codin/codinticketingapi/domain/ticketing/service/EventServiceTest.java
  src/test/java/inu/codin/codinticketingapi/domain/ticketing/service/ParticipationServiceTest.java
  src/test/java/inu/codin/codinticketingapi/domain/ticketing/service/TicketingServiceTest.java
Labels: enhancement

#41 fix: 사용자 이벤트 목록 및 상태별 목록 조회 버그 수정
  src/main/java/inu/codin/codinticketingapi/CodinTicketingApiApplication.java
  src/main/java/inu/codin/codinticketingapi/domain/admin/scheduler/EventStatusScheduler.java
  src/main/java/inu/codin/codinticketingapi/domain/ticketing/controller/EventController.java
  src/main/java/inu/codin/codinticketingapi/domain/ticketing/dto/response/ParticipationResponse.java
  src/main/java/inu/codin/codinticketingapi/domain/ticketing/repository/EventRepository.java
  src/main/java/inu/codin/codinticketingapi/domain/ticketing/scheduler/StockCheckJob.java
  src/main/java/inu/codin/codinticketingapi/domain/ticketing/service/EventService.java
  src/main/resources/application.yml
Labels: enhancement

#42 fix: 티켓팅 참여시 이벤트 상태 검증 로직 추가
  src/main/java/inu/codin/codinticketingapi/domain/ticketing/service/ParticipationService.java
Labels: bug

#44 배포 : 기능개선
  codin-ticketing-sse/src/main/java/inu/codin/codinticketingsse/CodinTicketingSseApplication.java
  src/main/java/inu/codin/codinticketingapi/domain/admin/controller/EventAdminControllerImpl.java
  src/main/java/inu/codin/codinticketingapi/domain/admin/controller/swagger/EventAdminController.java
  src/main/java/inu/codin/codinticketingapi/domain/admin/service/EventAdminService.java
  src/main/java/inu/codin/codinticketingapi/domain/admin/service/ExcelService.java
  src/main/java/inu/codin/codinticketingapi/domain/ticketing/dto/response/EventPageDetailResponse.java
  src/main/java/inu/codin/codinticketingapi/domain/ticketing/dto/response/EventPageResponse.java
  src/main/java/inu/codin/codinticketingapi/domain/ticketing/entity/Participation.java
  src/main/java/inu/codin/codinticketingapi/domain/ticketing/repository/ParticipationRepository.java
  src/main/java/inu/codin/codinticketingapi/domain/ticketing/service/EventService.java
  src/main/java/inu/codin/codinticketingapi/domain/ticketing/service/ParticipationService.java
  src/main/java/inu/codin/codinticketingapi/domain/ticketing/service/TicketingService.java
  src/test/java/inu/codin/codinticketingapi/domain/ticketing/service/TicketingServiceTest.java
Labels: enhancement

#45 refactor : 티켓 번호 발부를 위한 구현, 티켓팅 재참여 가능
  build.gradle
  codin-ticketing-sse/src/main/java/inu/codin/codinticketingsse/config/SecurityConfig.java
  src/main/java/inu/codin/codinticketingapi/CodinTicketingApiApplication.java
  src/main/java/inu/codin/codinticketingapi/config/RedisConfig.java
  src/main/java/inu/codin/codinticketingapi/config/SchedulerConfig.java
  src/main/java/inu/codin/codinticketingapi/domain/admin/controller/swagger/EventAdminController.java
  src/main/java/inu/codin/codinticketingapi/domain/admin/service/EventAdminService.java
  src/main/java/inu/codin/codinticketingapi/domain/ticketing/controller/EventController.java
  src/main/java/inu/codin/codinticketingapi/domain/ticketing/dto/response/ParticipationResponse.java
  src/main/java/inu/codin/codinticketingapi/domain/ticketing/redis/RedisEventService.java
  src/main/java/inu/codin/codinticketingapi/domain/ticketing/redis/RedisHealthCheckService.java
  src/main/java/inu/codin/codinticketingapi/domain/ticketing/repository/EventRepository.java
  src/main/java/inu/codin/codinticketingapi/domain/ticketing/repository/ParticipationRepository.java
  src/main/java/inu/codin/codinticketingapi/domain/ticketing/service/EventService.java
  src/main/java/inu/codin/codinticketingapi/domain/ticketing/service/ParticipationService.java
  src/main/java/inu/codin/codinticketingapi/domain/ticketing/service/TicketingService.java
Labels: enhancement

#46 refactor : 티켓 번호 발부를 위한 구현, 티켓팅 재참여 가능
  build.gradle
  codin-ticketing-sse/src/main/java/inu/codin/codinticketingsse/common/exception/GlobalExceptionHandler.java
  codin-ticketing-sse/src/main/java/inu/codin/codinticketingsse/config/SecurityConfig.java
  codin-ticketing-sse/src/main/java/inu/codin/codinticketingsse/security/exception/SecurityException.java
  src/main/java/inu/codin/codinticketingapi/CodinTicketingApiApplication.java
  src/main/java/inu/codin/codinticketingapi/config/RedisConfig.java
  src/main/java/inu/codin/codinticketingapi/config/SchedulerConfig.java
  src/main/java/inu/codin/codinticketingapi/domain/admin/controller/swagger/EventAdminController.java
  src/main/java/inu/codin/codinticketingapi/domain/admin/service/EventAdminService.java
  src/main/java/inu/codin/codinticketingapi/domain/ticketing/controller/EventController.java
  src/main/java/inu/codin/codinticketingapi/domain/ticketing/dto/response/ParticipationResponse.java
  src/main/java/inu/codin/codinticketingapi/domain/ticketing/redis/RedisEventService.java
  src/main/java/inu/codin/codinticketingapi/domain/ticketing/redis/RedisHealthCheckService.java
  src/main/java/inu/codin/codinticketingapi/domain/ticketing/repository/EventRepository.java
  src/main/java/inu/codin/codinticketingapi/domain/ticketing/repository/ParticipationRepository.java
  src/main/java/inu/codin/codinticketingapi/domain/ticketing/service/EventService.java
  src/main/java/inu/codin/codinticketingapi/domain/ticketing/service/ParticipationService.java
  src/main/java/inu/codin/codinticketingapi/domain/ticketing/service/TicketingService.java
Labels: enhancement
